apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kstats-opentelemetry-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kstats-opentelemetry-collector
subjects:
  - kind: ServiceAccount
    name: kstats-opentelemetry-collector
    namespace: kstats
